### ISSUE TITLE
cannot add watch face after build

### ISSUE THREAD

**Issue by naq219** [Nadeflore/tetriband#3]
Hello,
when i run build.sh . it error: `error: unknown option '-e' `
then  i deleted argument -e `for i in ../../assets/*.png; do wfjs convertPngToTga -i "$i"  png; done`
rebuild success. Add watch face to device success . 
But when i edit file watchface/index.js, rebuild , add watch face to device but not success

**Comment by Nadeflore** [comment]
Hi,
The reason you got the "error: unknown option '-e' " error, is because I added the -e parameter to watchface-js image converter but forgot to publish a new version.
I just published version 0.3.0 which includes the -e option
So upgrade it with

```bash
npm install -g watchface-js
```

Check you now have the 0.3.0 version
```bash
wfjs --version
```

and the build script should work with the -e option

If you still get errors after this, it might be because there errors in the changes you made. You can try running it with the official simulator to get console ouputs

**Comment by naq219** [comment]
Thank you.
can we continues run app when screen of? i use timer.createTimer but when screen of it not work
